title: 时间编织者
description: 一个融合了外星硅基文明、时间旅行、宇宙社会学、赛博朋克元素和王子复仇记的科幻史诗
theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/alexsuperai/zhuazhua-century/archive/main.zip
  tar_url: https://github.com/alexsuperai/zhuazhua-century/archive/main.tar.gz